<?php

namespace App\Controller;

use App\Dto\User\Input\UserRegisterInputDto;
use App\Dto\User\Input\UserUpdateInputDto;
use App\Dto\User\Output\UserOutputDto;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Attribute\Route;
use App\Service\UserService;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Lexik\Bundle\JWTAuthenticationBundle\Services\JWTTokenManagerInterface;

final class UserController extends AbstractController
{   
    
    //route to check if user is authenticated and connected
    #[Route('/api/user/checkAuthentication', methods: ['GET'])]
    public function checkUserAuthentication(UserService $userService): JsonResponse
    {
        $user = $userService->getAuthenticatedUser();

        if (!$user) {
            return new JsonResponse(['error' => 'User not authenticated'], 401);
        }

        $dto = new UserOutputDto($user->getUsername(), $user->getEmail() ?? '');
        return $this->json($dto);
    }
    
    // Route to get one user by ID
    #[Route('/api/user/{id}', methods: ['GET'])]
    public function showUser(int $id, UserService $userService): JsonResponse
    {
        $user = $userService->findUserById($id);

        if (!$user) {
            return new JsonResponse(['error' => 'User not found'], 404);
        }

        $dto = new UserOutputDto($user->getUsername(), $user->getEmail() ?? '');
        return $this->json($dto);
    }

    // Route to get all users
    #[Route('/api/user', methods: ['GET'])]
    public function getAllUsers(UserService $userService): JsonResponse
    {
        $users = $userService->getAllUsers();
        $dtos = [];

        foreach ($users as $user) {
            $dtos[] = new UserOutputDto($user->getUsername(), $user->getEmail() ?? '');
        }

        return $this->json($dtos);
    }

    // Route to register a new user
    #[Route('/api/user/register', methods: ['POST'])]
    public function register(
        Request $request,
        ValidatorInterface $validator,
        UserService $userService,
        JWTTokenManagerInterface $JWTManager
    ): JsonResponse {
        $data = json_decode($request->getContent(), true);
        $dto = new UserRegisterInputDto($data);

        $errors = $validator->validate($dto);
        if (count($errors) > 0) {
            $errorsArray = [];
            foreach ($errors as $error) {
                $errorsArray[$error->getPropertyPath()][] = $error->getMessage();
            }
            return new JsonResponse(['errors' => $errorsArray], JsonResponse::HTTP_BAD_REQUEST);
        }

        $user = $userService->createUser($dto);

        $jwt = $JWTManager->create($user);

        $response = new JsonResponse([
            'status' => 'User created',
            'id' => $user->getId(),
            'token' => $jwt,
        ], JsonResponse::HTTP_CREATED);

        return $response;
    }

    // Route to login a user
    // Note: Login is handled automatically by LexikJWTAuthenticationBundle
    // POST to /api/user/login_check with {"email": "user@example.com", "password": "..."}
    // The JWT token is generated by security.yaml firewall configuration


    // Route to delete a user by ID
    #[Route('/api/user/{id}', methods: ['DELETE'])]
    public function deleteUser(int $id, UserService $userService): JsonResponse
    {
        $user = $userService->findUserById($id);

        if (!$user) {
            return new JsonResponse(['error' => 'User not found'], 404);
        }

        try {
            $userService->deleteUser($user);
            return new JsonResponse(['status' => 'User deleted'], 204);
        } catch (\Exception $e) {
            return new JsonResponse(['error' => 'Deletion failed'], 500);
        }
    }

    // Route to update a user by ID
   #[Route('/api/user/{id}/update', methods: ['PUT'])]
    public function updateUser(
        int $id,
        Request $request,
        ValidatorInterface $validator,
        UserService $userService
    ): JsonResponse {
        $data = json_decode($request->getContent(), true);
        $dto = new UserUpdateInputDto($data); 

        $errors = $validator->validate($dto);
        if (count($errors) > 0) {
            $errorsArray = [];
            foreach ($errors as $error) {
                $errorsArray[$error->getPropertyPath()][] = $error->getMessage();
            }
            return new JsonResponse(['errors' => $errorsArray], 400);
        }

        try {
            $user = $userService->findUserById($id);
            $updatedUser = $userService->updateUser($user, $dto);

            return new JsonResponse([
                'status' => 'User updated',
                'id' => $updatedUser->getId(),
            ], 200);

        } catch (\App\Exception\UserNotFoundException $e) {
            return new JsonResponse(['error' => $e->getMessage()], 404);
        } catch (\Exception $e) {
            return new JsonResponse(['error' => 'Update failed'], 500);
        }

        }

    //route to logout user
    #[Route('/api/user/logout', methods: ['POST'])]
    public function logout(): JsonResponse
    {
    

        // The frontend should handle removing the JWT from localStorage.

        return new JsonResponse(['status' => 'User logged out']);
    }
}